apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-webapp
  template:
    metadata:
      labels:
        app: hello-world-webapp
    spec:
      containers:
      - name: hello-world-webapp
        image: <your-acr-name>.azurecr.io/hello-world-webapp:v1
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world-webapp
  ports:
    - protocol: TCP
      port: 8080 #external port
      targetPort: 3002
